name: flutter_opendroneid
description: A flutter plugin for reading Wi-Fi and Bluetooth Remote ID advertisements using native Android and iOS platform-specific implementation.
version: 0.15.2
repository: https://github.com/dronetag/flutter-opendroneid

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  device_info_plus: ^8.0.0
  dart_opendroneid: 
    git:
      url: git@github.com:dronetag/dart-opendroneid.git
      ref: feat/DT-2852-parse-auth-message

dev_dependencies:
  pigeon: ^10.1.6

flutter:
  plugin:
    platforms:
      android:
        package: cz.dronetag.flutter_opendroneid
        pluginClass: FlutterOpendroneidPlugin
      ios:
        pluginClass: FlutterOpendroneidPlugin