name: Publish to pub.dev

# Publish publishes the library to pub.dev

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g. "v2.31.0")'
        required: true
        type: string

env:
  FLUTTER_VERSION: "3.16.7"

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check successful release
        uses: dronetag/gha-shared/.github/actions/check-previous@check-previous-custom-ref
        with:
          workflow-name: Create Github release
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/${{ inputs.version }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.version }}
      - name: Install the project
        uses: dronetag/gha-shared/.github/actions/flutter-install@master
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          enforce-lockfile: false
      - name: Publish to pub.dev
        run: flutter pub publish -f --dry-run
