# A CI configuration to auto-publish pub packages.
# Taken from here: https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose

name: Publish

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'

jobs:
  publish:
    permissions:
      id-token: write 
      pull-requests: write
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    with:
      use-flutter: true
      sdk: '3.16.7'
