name: Create Github release

# Release workflow creates a new Github release
# with new version and updates changelog

on:
  push:
    branches:
      - master

env:
  FLUTTER_VERSION: "3.16.7"

jobs:
  release-version:
    # Prevent release commits from triggering release again
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    name: Release a new version
    uses: ./.github/workflows/create-release.yml
    concurrency: release-version-${{ github.repository }}
    with:
      install-changelog-plugin: true
      install-yq: true
      must-release: false
      create-github-release: false
    secrets:
      pat-token: ${{ secrets.PATTEST }}
