name: Create Github release

# Release workflow creates a new Github release
# with new version and updates changelog

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Do not run release on post-release commit

env:
  FLUTTER_VERSION: "3.16.7"

jobs:
  # integration:
  #   name: Run integration
  #   uses: ./.github/workflows/integration.yml

  release-version:
    name: Release a new version
    # needs: integration
    uses: ./.github/workflows/create-release.yml
    concurrency: release-version-${{ github.repository }}
    with:
      install-changelog-plugin: true
      install-yq: true
      must-release: false
      create-github-release: false
    secrets:
      pat-token: ${{ secrets.PATTEST }}
